(define-module (sveb packages jetbrainsmono-nerd-font)
               #:use-module (guix utils)
               #:use-module ((guix licenses) #:prefix license:)
               #:use-module (guix packages)
               #:use-module (guix download)
               #:use-module (guix gexp)
               #:use-module (guix git-download)
               #:use-module (guix build-system font)
               #:use-module (guix build-system gnu)
               #:use-module (guix build-system meson)
               #:use-module (guix build-system trivial)
               #:use-module (gnu packages c)
               #:use-module (gnu packages base)
               #:use-module (gnu packages bash)
               #:use-module (gnu packages compression)
               #:use-module (gnu packages fontutils)
               #:use-module (gnu packages gd)
               #:use-module (gnu packages gettext)
               #:use-module (gnu packages glib)
               #:use-module (gnu packages gtk)
               #:use-module (gnu packages perl)
               #:use-module (gnu packages pkg-config)
               #:use-module (gnu packages python)
               #:use-module (gnu packages python-xyz))

(define-public jetbrainsmono-nerd-font
  (package
    (name "JetBrainsMono-Nerd-Font")
    (version "3.2.1")
    (build-system font-build-system)
    (synopsis "Patched JetBrainsMono Nerd Font")
    (home-page "https://github.com/ryanoasis/nerd-fonts")
   ))
    
